# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ticker_fetcher}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt White"]
  s.date = %q{2010-05-25}
  s.description = %q{Retrieves tickers, and names for all securities listed on the 3 major US exchanges (NYSE, NASDAQ, AMEX).}
  s.email = %q{mattw922@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/ticker_fetcher.rb",
     "test/amex_test_data.csv",
     "test/helper.rb",
     "test/nasd_test_data.csv",
     "test/nyse_test_data.csv",
     "test/test_ticker_fetcher.rb",
     "ticker_fetcher-0.1.0.gem",
     "ticker_fetcher.gemspec"
  ]
  s.homepage = %q{http://github.com/whitethunder/ticker_fetcher}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Fetches all tickers for NYSE, NASDAQ, and AMEX exchanges.}
  s.test_files = [
    "test/test_ticker_fetcher.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<fastercsv>, [">= 1.5.0"])
      s.add_development_dependency(%q<flexmock>, [">= 0.8.2"])
    else
      s.add_dependency(%q<fastercsv>, [">= 1.5.0"])
      s.add_dependency(%q<flexmock>, [">= 0.8.2"])
    end
  else
    s.add_dependency(%q<fastercsv>, [">= 1.5.0"])
    s.add_dependency(%q<flexmock>, [">= 0.8.2"])
  end
end

